added Pending Async as status for transaction
jembi/openhim-core-js pull request #1207
Opened 2023-09-08 06:06 UTC by brett-onions

Updating backend to allow transaction status of "Pending Async" TB-162

2023-09-13 09:57 UTC, bradsawadye commented on src/middleware/messageStore.js
> +  // updates the status code that appears to for the client
typo

2023-09-13 10:00 UTC, bradsawadye commented on src/middleware/messageStore.js
> +  ctx.response.status = status;
Remove statement terminator for consistency

2023-09-13 10:03 UTC, bradsawadye commented on src/middleware/messageStore.js
> +
Remove empty lines

2023-09-13 10:03 UTC, bradsawadye commented on src/model/channels.js
> +    required: false,
default for required is false. We can remove this line

2023-09-13 10:38 UTC, bradsawadye commented
@brett-onions looks good. Please add some tests

2023-09-21 14:56 UTC, Lumiere-Lodi approved these changes
Looks good now with the tests.

2023-09-25 08:51 UTC, nour-borgi requested changes

2023-09-25 08:51 UTC, nour-borgi commented on src/middleware/messageStore.js
> +            tx.status = transactionStatus.PENDING_ASYNC
```suggestion
          if(isAsynchronousProcess){
            tx.status = transactionStatus.PENDING_ASYNC
```

And please don't forget to run `npm run lint`  and `npm run lint:fix` to lint these changes

2023-09-28 07:41 UTC, arran-standish submitted a review, later dismissed
looks good

2023-09-28 07:57 UTC, nour-borgi commented on src/middleware/messageStore.js
> +          ) {
```suggestion
          if (isAsynchronousProcess) {
```

2023-09-28 08:36 UTC, nour-borgi approved these changes
LGTM

2023-09-28 14:00 UTC, nour-borgi approved these changes
LGTM

2023-10-03 10:07 UTC, MatthewErispe commented
this is pending bug fix https://jembiprojects.jira.com/browse/TB-202

2023-10-05 07:10 UTC, MatthewErispe submitted a review, later dismissed
@brett-onions happy with the bug fix change

2023-10-13 10:21 UTC, nour-borgi approved these changes

2023-10-13 10:55 UTC, MatthewErispe approved these changes

2023-10-13 10:56 UTC, merged